vars:
  - B_CORP_DATADIR: src/themes/sustainable-growth/b-corporations/_data
stages:
  b-corp:
    always_changed: true
    wdir: ../
    cmd: perl pipelines/b-corp.pl
    deps:
      - pipelines/b-corp.pl
      - pipelines/lib.pl
    outs: 
      # - ${DATADIR}/bcorp_list.csv:
      #     cache: false
      - ${B_CORP_DATADIR}/bcorp_by_la.csv:
          cache: false
      - ${B_CORP_DATADIR}/bcorp_north.csv:
          cache: false
      - ${B_CORP_DATADIR}/updated.yaml:
          cache: false
  edd_dictionary:
    wdir: ../
    cmd: python pipelines/edd_dictionary.py
    deps:
      - pipelines/edd_dictionary.py
      - https://raw.githubusercontent.com/economic-analytics/edd/main/data/edd_dict.csv
    outs:
      - src/_data/edd_dictionary.yaml:
          cache: false