vars:
  - TOP: ../..
stages:
  vacancies:
    cmd: PYTHONPATH=${TOP} python vacancies.py
    deps:
      - vacancies.py
      - ${TOP}/pipelines/util.py
      - ${TOP}/working/cs/vacancies_by_sector_percentage_change_on_previous.csv
      - https://github.com/economic-analytics/edd/raw/main/data/parquet/LMS.parquet
    outs:
      - ${TOP}/src/themes/people-skills-future/_data/growth_by_sector.csv:
          cache: false
      - ${TOP}/src/themes/people-skills-future/_data/vacancies_by_sector.csv:
          cache: false
  employment:
    cmd: PYTHONPATH=${TOP} python employment.py
    deps:
      - employment.py
      - ${TOP}/pipelines/util.py
      - ${TOP}/working/cs/cs-true-north.csv
    outs:
      - ${TOP}/src/themes/people-skills-future/_data/unemployment.csv:
          cache: false
  qualifications:
    cmd: PYTHONPATH=${TOP} python qualifications.py
    deps:
      - qualifications.py
      - ${TOP}/pipelines/util.py
      - ${TOP}/working/cs/cs-true-north.csv
    outs:
      - ${TOP}/src/themes/people-skills-future/_data/nvq_3plus.csv:
          cache: false