vars:
  - TOP: ../..
stages:
  vacancies:
    cmd: PYTHONPATH=${TOP} python vacancies.py
    deps:
      - vacancies.py
      - ${TOP}/pipelines/util.py
      - https://github.com/economic-analytics/edd/raw/main/data/parquet/LMS.parquet
    outs:
      - ${TOP}/src/themes/people-skills-future/_data/vacancies_yearly_change_by_sector.csv:
          cache: false
      - ${TOP}/src/themes/people-skills-future/_data/vacancies_by_sector.csv:
          cache: false
  employment:
    cmd: PYTHONPATH=${TOP} python employment.py
    deps:
      - employment.py
      - ${TOP}/pipelines/util.py
      - ${TOP}/working/cs/cs-true-north.csv
      - ${TOP}/working/cs/nomis-lad.csv
    outs:
      - ${TOP}/src/themes/people-skills-future/_data/employment.csv:
          cache: false
      - ${TOP}/src/themes/people-skills-future/_data/economic_inactivity.csv:
          cache: false
      - ${TOP}/src/themes/people-skills-future/_data/employment_LAD.csv:
          cache: false
      - ${TOP}/src/themes/people-skills-future/_data/economic_inactivity_LAD.csv:
          cache: false
  qualifications:
    cmd: PYTHONPATH=${TOP} python qualifications.py
    deps:
      - qualifications.py
      - ${TOP}/pipelines/util.py
      - ${TOP}/working/cs/cs-true-north.csv
    outs:
      - ${TOP}/src/themes/people-skills-future/_data/nvq_4plus.csv:
          cache: false
  neet:
    cmd: PYTHONPATH=${TOP} python neet.py
    deps:
      - neet.py
      - https://raw.githubusercontent.com/open-innovations/yff-data-pipelines/main/data/processed/neet.csv
      - https://raw.githubusercontent.com/open-innovations/yff-data-pipelines/main/data/processed/yff/neet-factors.csv
    outs:
      - ${TOP}/src/themes/people-skills-future/_data/neet.csv:
          cache: false
      - ${TOP}/src/themes/people-skills-future/_data/risk_of_neet_by_la.csv:
          cache: false